---
title: "writing_functions"
author: "Kaila Boyer"
date: "11/4/2021"
output: github_document
---


```{r}
library(tidyverse)
library(rvest)

set.seed(1)
```



## Z scores 

```{r}
x_vec <- rnorm(25, mean = 5, sd=4)

(x_vec - mean(x_vec)) / sd(x_vec)

z_scores = function(x) {
  
  z = (x-mean(x)) / sd(x)
  
  return(z)
}

z_scores(x = x_vec)


y_vec <- rnorm(40, mean = 12, sd=0.3)
z_scores(y_vec)

```

How great is this? 

only kinda great 

```{r, error = TRUE}
z_scores(3)

z_scores(c("my", "name", "is", "kaila"))

z_scores(mtcars)
```

try again 
```{r, error = TRUE}
z_scores = function(x) { 
  if(!is.numeric(x)) { 
    stop("x needs to be numeric")
  }
  
  if(length(x) < 3) { 
    stop("x should have at least 3 numbers")
  }
}

z_scores(mtcars)
```

```{r}
z_scores = function(x) {
  
  z = (x-mean(x)) / sd(x)
  
  return(z)
}

```

```{r}

mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  list(mean = mean_x, 
       sd = sd_x)
}


mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  output_df = tibble(
    mean = mean_x, 
    sd = sd_x
  )
  return(output_df)
}


```

```{r}
sim_data <- tibble( 
  x = rnorm(30, mean= 2, sd=3)
  )

sim_data %>% summarize(
  mean = mean(x), 
  sd = sd(x)
)
```

Let's write a function that simulates data, computes mean and sd 
```{r}
sim_mean_sd = function(n, mu, sigma) {
  
    sim_data = tibble( 
      x = rnorm(n, mean = mu, sd = sigma)
      )
    
    sim_data %>% summarize(
      mean = mean(x), 
      sd = sd(x)
      )

  
}

sim_mean_sd(30, 4, 3)
sim_mean_sd(n = 30, mu = 4, sigma = 3)

sim_data
```



